{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "check-reviewer-no-commit.fullname" . }}
  labels:
    {{- include "check-reviewer-no-commit.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_ID: {{ .Values.app.appId | quote }}
  WEBHOOK_SECRET: {{ .Values.app.webhookSecret | quote }}
  PRIVATE_KEY: {{ .Values.app.privateKey | quote }}
{{- end }}
